language: node_js

sudo: required

node_js:
  - "8"

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g truffle ganache-cli solium solidity-coverage coveralls

install:
  - npm install

script:
  - solium -d .
  - testrpc &
  - SOLIDITY_COVERAGE=true truffle test

after_success:
  - node_modules/.bin/solidity-coverage
  - coverage/lcov.info | coveralls
