language: node_js

sudo: required

node_js:
  - "8"

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - export PATH=$PATH:$PWD/node_modules/.bin/

script:
  - npm run lint
  - npm run lint:sol
  - ganache-cli &
  - solidity-coverage
  - cat coverage/lcov.info | coveralls
