language: node_js

sudo: required

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - export PATH=$PATH:$PWD/node_modules/.bin/

script:
  - npm run lint
  - npm run lint:sol
  - ganache-cli &
  - solidity-coverage
  - cat coverage/lcov.info | coveralls
